name: Build and deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.1
    
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Build wasm
        run: |
          cd wasm
          GOARCH=wasm GOOS=js go build -o main.wasm
          cd ..
        
      - name: Install and Build
        run: |
          cd verify_web
          npm install
          npm run build

      # Runs deploy commands
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: verify_web/public